# docker compose version
version: "2.0"

# site services
services:
  site:
    build: .
    ports:
      - "80:80"
  memcached:
    image: memcached:alpine
    ports:
      - "11211:11211"
    mem_limit: 64m
    command: memcached -m 4m
